<% require "dotenv"; Dotenv.load(".env") %>

service: blog-space
image: kamaldh1/blog-space ## change username

servers:
  web:
    hosts:
     - 000.000.000.000 ## change ip

  worker:
    hosts:
      - 000.000.000.000 ## change ip
    cmd: bundle exec sidekiq

proxy:
  ssl: true
  host: app.00000000.xyz  ## change domain

registry:
  username: kamaldh1 ## change username
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@999.999.999.999 ## change IP


env:
  clear:
    RAILS_ENV: production
    POSTGRES_HOST: blog-space-postgres
    POSTGRES_USER: blog-space
    POSTGRES_DB: blog_space_production
  secret:
    - SECRET_KEY_BASE
    - POSTGRES_PASSWORD
    - REDIS_URL

asset_path: /rails/public/assets

accessories:
  postgres:
    image: "postgres:16-alpine"
    host: 000.000.000.000 ## change ip
    env:
      clear:
        POSTGRES_USER: "blog-space"
        POSTGRES_DB: "blog_space_production"
      secret:
        - POSTGRES_PASSWORD
    directories:
      - "data:/var/lib/postgresql/data"
    options:
      shm-size: "128mb"

  redis:
    image: "redis:7.2-alpine"
    host: 000.000.000.000 ## change ip
    directories:
      - data:/data
    cmd: redis-server --requirepass <%= ENV["REDIS_PASSWORD"] %>
